//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string UserId { get; set; }
        public int ArticleId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
