//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flower()
        {
            this.PlantationFlowers1 = new HashSet<PlantationFlower>();
            this.SupplyFlowers = new HashSet<SupplyFlower>();
            this.WarehouseFlowers = new HashSet<WarehouseFlower>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public string NameLatin2 { get; set; }
        public string FlowerFamily { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantationFlower> PlantationFlowers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyFlower> SupplyFlowers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseFlower> WarehouseFlowers { get; set; }
    }
}
