//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerTerritory
    {
        public int PartnerId { get; set; }
        public string TerritoryId { get; set; }
        public int PartnerId1 { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
