//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantationFlower
    {
        public int Id { get; set; }
        public Nullable<int> FlowerId { get; set; }
        public Nullable<int> PlantationId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Flower Flower1 { get; set; }
        public virtual Plantation Plantation { get; set; }
    }
}
