//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Deals = new HashSet<Deal>();
            this.Partners = new HashSet<Partner>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string FounderId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FounderId1 { get; set; }
        public Nullable<int> ProjectDetailsProjectId { get; set; }
        public string Background { get; set; }
        public string FullDescription { get; set; }
        public string RisksAndChallenges { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> StartBudget { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner> Partners { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
