//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseFlower
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public int FlowerId { get; set; }
        public int WarehouseId { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
